services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    env_file:
      - vaultwarden.env
    environment:
      - USE_SYSLOG=true
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
    volumes:
      - ./vw-data/:/data/
    restart: always
    networks:
      - vaultwarden
    user: 1000:1000

  vaultwarden-db:
    image: "mariadb"
    container_name: "mysql"
    restart: always
    env_file:
      - vaultwarden.env
    volumes:
      - ./vw-db/:/var/lib/mysql
    networks:
      - vaultwarden

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: vaultwarden-cloudflared
    env_file:
      - vaultwarden.env
    command: tunnel run $TUNNEL_ID
    restart: unless-stopped
    networks:
      - vaultwarden
    user: 1000:1000

networks:
  vaultwarden:
    name: vaultwarden
    external: true

volumes:
  vw-data:
  vw-db:
