services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    env_file:
      - vaultwarden.env
    environment:
      - USE_SYSLOG=true
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
      # The connectiopn string for the database
      - DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE
    volumes:
      - vaultwarden:/data/
    restart: always
    networks:
      - vaultwarden
    depends_on:
      vaultwarden-db:
        condition: service_healthy
    healthcheck:
      test: curl -s -L http://localhost:80/alive
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 55

  vaultwarden-db:
    image: "mariadb:latest"
    container_name: "mysql"
    restart: always
    env_file:
      - vaultwarden.env
    volumes:
      - vaultwarden_db:/var/lib/mysql
    networks:
      - vaultwarden
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 55

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: vaultwarden-cloudflared
    env_file:
      - vaultwarden.env
    command: tunnel run
    restart: unless-stopped
    depends_on:
      vaultwarden:
        condition: service_healthy
    networks:
      - vaultwarden
    user: 1000:1000

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - fail2ban_config:/config
      - /var/log:/var/log:ro
    restart: always

networks:
  vaultwarden:
    name: vaultwarden

volumes:
  vaultwarden:
  vaultwarden_db:
  fail2ban_config:
